name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        SSO_USERNAME: ${{ secrets.SSO_USERNAME }}
        SSO_PASSWORD: ${{ secrets.SSO_PASSWORD }}
        SKIP_EXPECT: ${{ secrets.SKIP_EXPECT }}
      run: yarn playwright test
    - name: Build report
      run: yarn build
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: dist
        path: dist/
        retention-days: 30
